### PR TITLE
The regex version of dns parsing with port number support

### PR DESCRIPTION
**Pull request by saki7**
@zussel Can you review this one? General suggestions are welcome, and also I'm not quite sure about the mssql's "instance" variable - is it even used in somewhere?

Closes issue #61.

### CODE REVIEW

**Comment by saki7** [comment]
Oops! I think I missed the password restrictions... There seems like no restrictions on the length of a password or characters supported. So I need to make the regex wildcard.

**Comment by saki7** [comment]
Referring to http://dev.mysql.com/doc/refman/5.7/en/identifiers.html:

I was so surprised that you could create such a database like this:
```
mysql> CREATE DATABASE `really@strange*database$name`;
```

So I've loosened the constraints a lot more.
Hopefully this should work in most cases.

**Comment by zussel** [comment]
I've merged your pull request so far. It's much more readable than the original piece of code.

May one can think about a unified parser for all backends. But I'm unsure how the sqlite connection string my fit.

**Comment by saki7** [comment]
IMO it's ok to have the parser being split for now - it possibly could lead us to create an original brand-new dns syntax for the unified parser. We may reconsider about it later when something bad happens.

**Pull request merged**
